In [46]:
import pandas as pd
import numpy as np

In [47]:
dados_brutos = pd.read_csv(r'C:\Users\Rafael Tomé\OneDrive\Área de Trabalho\Analises\Portifólio de projetos\Projeto Imobiliaria\imoveis.csv', sep=';')

In [96]:
dados_brutos

,Bairros,Valores,Informações,Descricao
0,"Blumenau, Escola Agrícola\nCód.: 1807","R$ 380.000,00","2 quartos\n2 vagas\n80,0 m²",Casa no Bairro Escola Agrícola em Blumenau com...
1,"Blumenau, Velha\nCód.: 2007","R$ 480.000,00","3 quartos\n1 suíte\n131,0 m²",Casa no Bairro Velha em Blumenau com 3 Dormitó...
2,"Blumenau, Victor Konder\nCód.: 3478924","R$ 375.000,00","2 quartos\n1 suíte\n1 vaga\n124,0 m²",Apartamento no Bairro Victor Konder em Blumena...
3,"Blumenau, Salto Weissbach\nCód.: CA0133","R$ 420.000,00","2 quartos\n2 vagas\n74,0 m²",Casa no Bairro Salto Weissbach em Blumenau com...
4,"Blumenau, Valparaiso\nCód.: 609","R$ 400.000,00","5 quartos\n3 vagas\n200,0 m²",Casa no Bairro Valparaiso em Blumenau com 5 Do...
...,...,...,...,...
18157,"Blumenau, Vila Itoupava\nCód.: CA0061","R$ 280.000,00","3 quartos\n3 vagas\n150,0 m²",Casa no Bairro Vila Itoupava em Blumenau com 3...
18158,"Blumenau, Salto Norte\nCód.: CA0817","R$ 450.000,00",3 quartos,Casa no Bairro Salto Norte em Blumenau com 3 D...
18159,"Blumenau, Centro\nCód.: CA0008","R$ 950.000,00","4 quartos\n8 vagas\n300,0 m²",Casa no Bairro Centro em Blumenau com 4 Dormit...
18160,"Blumenau, Água Verde\nCód.: 7010607","R$ 580.000,00",3 quartos\n1 suíte\n2 vagas,Casa no Bairro Água Verde em Blumenau com 3 Do...
18161,"Blumenau, Vila Nova\nCód.: 5121321","R$ 750.000,00",2 quartos\n1 vaga,Casa no Bairro Vila Nova em Blumenau com 2 Dor...

In [97]:
imoveis = dados_brutos.copy()

In [98]:
imoveis['Bairros'] = imoveis['Bairros'].apply(lambda x: x.split(',')[1].split('\n')[0].strip() if ',' in x else x)
imoveis['Bairros']

0        Escola Agrícola
1                  Velha
2          Victor Konder
3        Salto Weissbach
4             Valparaiso
              ...
18157      Vila Itoupava
18158        Salto Norte
18159             Centro
18160         Água Verde
18161          Vila Nova
Name: Bairros, Length: 18162, dtype: object

In [99]:
imoveis['Bairros'].unique()

array(['Escola Agrícola', 'Velha', 'Victor Konder', 'Salto Weissbach',
       'Valparaiso', 'Água Verde', 'Itoupava Seca', 'Fortaleza', 'Centro',
       'Salto', 'Itoupava Central', 'Jardim Blumenau', 'Itoupavazinha',
       'Itoupava Norte', 'Vila Nova', 'Vorstadt', 'Velha Central',
       'Salto Norte', 'Fortaleza Alta', 'Boa Vista', 'Ponta Aguda',
       'Vila Formosa', 'Fidelis', 'Nova Esperança', 'Progresso',
       'Ribeirão Fresco', 'Garcia', 'Testo Salto', 'Velha Grande',
       'Passo Manso', 'Tribess', 'Belchior Central', 'Badenfurt',
       'Bom Retiro', 'Glória', 'Vila Itoupava', 'Blumenau\nCód.: 6301173'],
      dtype=object)

In [100]:
imoveis = imoveis[imoveis['Bairros'] != 'Blumenau\nCód.: 6301173']

In [102]:
imoveis[imoveis['Valores'] == 'CONSULTAR']

,Bairros,Valores,Informações,Descricao
1426,Garcia,CONSULTAR,NaN,Apartamento no Bairro Garcia em Blumenau - 330...
2834,Salto Weissbach,CONSULTAR,"2 quartos\n2 suítes\n2 vagas\n91,0 m²",Apartamento no Bairro Salto Weissbach em Blume...
4653,Ponta Aguda,CONSULTAR,"4 quartos\n4 suítes\n3 vagas\n265,0 m²",Apartamento no Bairro Ponta Aguda em Blumenau ...
4654,Itoupava Central,CONSULTAR,"3 quartos\n1 suíte\n3 vagas\n61,0 m²",Apartamento no Bairro Itoupava Central em Blum...
9656,Itoupava Central,CONSULTAR,NaN,Apartamento no Bairro Itoupava Central em Blum...
9657,Jardim Blumenau,CONSULTAR,4 quartos\n4 suítes\n4 vagas,Apartamento no Bairro Jardim Blumenau em Blume...
14247,Jardim Blumenau,CONSULTAR,"4 quartos\n4 suítes\n4 vagas\n276,0 m²",Apartamento no Bairro Jardim Blumenau em Blume...
16007,Jardim Blumenau,CONSULTAR,"4 quartos\n4 suítes\n3 vagas\n276,9 m²",Apartamento no Bairro Jardim Blumenau em Blume...

In [103]:
# Remover as linhas onde a coluna 'Valores' é 'CONSULTAR'
imoveis = imoveis[imoveis['Valores'] != 'CONSULTAR']

# Agora, converter os valores numéricos corretamente
imoveis['Valores'] = imoveis['Valores'].apply(lambda x: int(x.replace('R$', '').replace('.', '').replace(',', '').strip()))

imoveis

,Bairros,Valores,Informações,Descricao
0,Escola Agrícola,38000000,"2 quartos\n2 vagas\n80,0 m²",Casa no Bairro Escola Agrícola em Blumenau com...
1,Velha,48000000,"3 quartos\n1 suíte\n131,0 m²",Casa no Bairro Velha em Blumenau com 3 Dormitó...
2,Victor Konder,37500000,"2 quartos\n1 suíte\n1 vaga\n124,0 m²",Apartamento no Bairro Victor Konder em Blumena...
3,Salto Weissbach,42000000,"2 quartos\n2 vagas\n74,0 m²",Casa no Bairro Salto Weissbach em Blumenau com...
4,Valparaiso,40000000,"5 quartos\n3 vagas\n200,0 m²",Casa no Bairro Valparaiso em Blumenau com 5 Do...
...,...,...,...,...
18157,Vila Itoupava,28000000,"3 quartos\n3 vagas\n150,0 m²",Casa no Bairro Vila Itoupava em Blumenau com 3...
18158,Salto Norte,45000000,3 quartos,Casa no Bairro Salto Norte em Blumenau com 3 D...
18159,Centro,95000000,"4 quartos\n8 vagas\n300,0 m²",Casa no Bairro Centro em Blumenau com 4 Dormit...
18160,Água Verde,58000000,3 quartos\n1 suíte\n2 vagas,Casa no Bairro Água Verde em Blumenau com 3 Do...
18161,Vila Nova,75000000,2 quartos\n1 vaga,Casa no Bairro Vila Nova em Blumenau com 2 Dor...

In [104]:
imoveis['Valores'] = (imoveis['Valores'] / 100).round(0)
imoveis

,Bairros,Valores,Informações,Descricao
0,Escola Agrícola,380000.0,"2 quartos\n2 vagas\n80,0 m²",Casa no Bairro Escola Agrícola em Blumenau com...
1,Velha,480000.0,"3 quartos\n1 suíte\n131,0 m²",Casa no Bairro Velha em Blumenau com 3 Dormitó...
2,Victor Konder,375000.0,"2 quartos\n1 suíte\n1 vaga\n124,0 m²",Apartamento no Bairro Victor Konder em Blumena...
3,Salto Weissbach,420000.0,"2 quartos\n2 vagas\n74,0 m²",Casa no Bairro Salto Weissbach em Blumenau com...
4,Valparaiso,400000.0,"5 quartos\n3 vagas\n200,0 m²",Casa no Bairro Valparaiso em Blumenau com 5 Do...
...,...,...,...,...
18157,Vila Itoupava,280000.0,"3 quartos\n3 vagas\n150,0 m²",Casa no Bairro Vila Itoupava em Blumenau com 3...
18158,Salto Norte,450000.0,3 quartos,Casa no Bairro Salto Norte em Blumenau com 3 D...
18159,Centro,950000.0,"4 quartos\n8 vagas\n300,0 m²",Casa no Bairro Centro em Blumenau com 4 Dormit...
18160,Água Verde,580000.0,3 quartos\n1 suíte\n2 vagas,Casa no Bairro Água Verde em Blumenau com 3 Do...
18161,Vila Nova,750000.0,2 quartos\n1 vaga,Casa no Bairro Vila Nova em Blumenau com 2 Dor...

In [105]:
# Substituir '\n' por '|' na coluna 'Informações'
imoveis['Informações'] = imoveis['Informações'].replace('\n', ' | ', regex=True)

imoveis

,Bairros,Valores,Informações,Descricao
0,Escola Agrícola,380000.0,"2 quartos | 2 vagas | 80,0 m²",Casa no Bairro Escola Agrícola em Blumenau com...
1,Velha,480000.0,"3 quartos | 1 suíte | 131,0 m²",Casa no Bairro Velha em Blumenau com 3 Dormitó...
2,Victor Konder,375000.0,"2 quartos | 1 suíte | 1 vaga | 124,0 m²",Apartamento no Bairro Victor Konder em Blumena...
3,Salto Weissbach,420000.0,"2 quartos | 2 vagas | 74,0 m²",Casa no Bairro Salto Weissbach em Blumenau com...
4,Valparaiso,400000.0,"5 quartos | 3 vagas | 200,0 m²",Casa no Bairro Valparaiso em Blumenau com 5 Do...
...,...,...,...,...
18157,Vila Itoupava,280000.0,"3 quartos | 3 vagas | 150,0 m²",Casa no Bairro Vila Itoupava em Blumenau com 3...
18158,Salto Norte,450000.0,3 quartos,Casa no Bairro Salto Norte em Blumenau com 3 D...
18159,Centro,950000.0,"4 quartos | 8 vagas | 300,0 m²",Casa no Bairro Centro em Blumenau com 4 Dormit...
18160,Água Verde,580000.0,3 quartos | 1 suíte | 2 vagas,Casa no Bairro Água Verde em Blumenau com 3 Do...
18161,Vila Nova,750000.0,2 quartos | 1 vaga,Casa no Bairro Vila Nova em Blumenau com 2 Dor...

In [106]:
# Função para extrair os dados das novas colunas, retornando 0 quando não encontrar valores
def extrair_informacoes(info):
    if isinstance(info, str):  # Verifica se o valor é uma string
        # Separar as informações por '|'
        partes = info.split(' | ')
        
        # Extrair os valores para cada coluna
        quartos = next((p for p in partes if 'quarto' in p.lower()), '0')
        suites = next((p for p in partes if 'suíte' in p.lower()), '0')
        vagas = next((p for p in partes if 'vaga' in p.lower()), '0')
        tamanho = next((p for p in partes if 'm²' in p.lower()), '0')
        
        # Retornar os valores limpos
        return [quartos, suites, vagas, tamanho]
    else:
        # Retornar 0 para casos não string
        return ['0', '0', '0', '0']

# Aplicar a função à coluna 'Informações'
imoveis[['Quartos', 'Suítes', 'Vagas', 'Tamanho']] = imoveis['Informações'].apply(extrair_informacoes).apply(pd.Series)

# Limpar os valores de cada coluna (remover textos e converter para numérico)
imoveis['Quartos'] = imoveis['Quartos'].str.extract('(\d+)').astype(float).fillna(0)
imoveis['Suítes'] = imoveis['Suítes'].str.extract('(\d+)').astype(float).fillna(0)
imoveis['Vagas'] = imoveis['Vagas'].str.extract('(\d+)').astype(float).fillna(0)
imoveis['Tamanho'] = imoveis['Tamanho'].str.extract('(\d+,\d+|\d+)').replace(',', '.', regex=True).astype(float).fillna(0)

# Exibir o DataFrame com as novas colunas
imoveis[['Quartos', 'Suítes', 'Vagas', 'Tamanho']]

       Quartos  Suítes  Vagas  Tamanho
0          2.0     0.0    2.0     80.0
1          3.0     1.0    0.0    131.0
2          2.0     1.0    1.0    124.0
3          2.0     0.0    2.0     74.0
4          5.0     0.0    3.0    200.0
...        ...     ...    ...      ...
18157      3.0     0.0    3.0    150.0
18158      3.0     0.0    0.0      0.0
18159      4.0     0.0    8.0    300.0
18160      3.0     1.0    2.0      0.0
18161      2.0     0.0    1.0      0.0

[18153 rows x 4 columns]

In [107]:
imoveis

,Bairros,Valores,Informações,Descricao,Quartos,Suítes,Vagas,Tamanho
0,Escola Agrícola,380000.0,"2 quartos | 2 vagas | 80,0 m²",Casa no Bairro Escola Agrícola em Blumenau com...,2.0,0.0,2.0,80.0
1,Velha,480000.0,"3 quartos | 1 suíte | 131,0 m²",Casa no Bairro Velha em Blumenau com 3 Dormitó...,3.0,1.0,0.0,131.0
2,Victor Konder,375000.0,"2 quartos | 1 suíte | 1 vaga | 124,0 m²",Apartamento no Bairro Victor Konder em Blumena...,2.0,1.0,1.0,124.0
3,Salto Weissbach,420000.0,"2 quartos | 2 vagas | 74,0 m²",Casa no Bairro Salto Weissbach em Blumenau com...,2.0,0.0,2.0,74.0
4,Valparaiso,400000.0,"5 quartos | 3 vagas | 200,0 m²",Casa no Bairro Valparaiso em Blumenau com 5 Do...,5.0,0.0,3.0,200.0
...,...,...,...,...,...,...,...,...
18157,Vila Itoupava,280000.0,"3 quartos | 3 vagas | 150,0 m²",Casa no Bairro Vila Itoupava em Blumenau com 3...,3.0,0.0,3.0,150.0
18158,Salto Norte,450000.0,3 quartos,Casa no Bairro Salto Norte em Blumenau com 3 D...,3.0,0.0,0.0,0.0
18159,Centro,950000.0,"4 quartos | 8 vagas | 300,0 m²",Casa no Bairro Centro em Blumenau com 4 Dormit...,4.0,0.0,8.0,300.0
18160,Água Verde,580000.0,3 quartos | 1 suíte | 2 vagas,Casa no Bairro Água Verde em Blumenau com 3 Do...,3.0,1.0,2.0,0.0
18161,Vila Nova,750000.0,2 quartos | 1 vaga,Casa no Bairro Vila Nova em Blumenau com 2 Dor...,2.0,0.0,1.0,0.0

In [108]:
# Função para classificar a descrição como 'Casa', 'Apartamento' ou 'Outro'
def classificar_tipo(descricao):
    if isinstance(descricao, str):
        if 'Casa' in descricao:
            return 'Casa'
        elif 'Apartamento' in descricao:
            return 'Apartamento'
    return 'Outro'  # Retorna 'Outro' se não for uma string ou não houver correspondência

# Aplicar a função à coluna 'Descricao'
imoveis['Tipo'] = imoveis['Descricao'].apply(classificar_tipo)

# Exibir o DataFrame com a nova coluna
imoveis

,Bairros,Valores,Informações,Descricao,Quartos,Suítes,Vagas,Tamanho,Tipo
0,Escola Agrícola,380000.0,"2 quartos | 2 vagas | 80,0 m²",Casa no Bairro Escola Agrícola em Blumenau com...,2.0,0.0,2.0,80.0,Casa
1,Velha,480000.0,"3 quartos | 1 suíte | 131,0 m²",Casa no Bairro Velha em Blumenau com 3 Dormitó...,3.0,1.0,0.0,131.0,Casa
2,Victor Konder,375000.0,"2 quartos | 1 suíte | 1 vaga | 124,0 m²",Apartamento no Bairro Victor Konder em Blumena...,2.0,1.0,1.0,124.0,Apartamento
3,Salto Weissbach,420000.0,"2 quartos | 2 vagas | 74,0 m²",Casa no Bairro Salto Weissbach em Blumenau com...,2.0,0.0,2.0,74.0,Casa
4,Valparaiso,400000.0,"5 quartos | 3 vagas | 200,0 m²",Casa no Bairro Valparaiso em Blumenau com 5 Do...,5.0,0.0,3.0,200.0,Casa
...,...,...,...,...,...,...,...,...,...
18157,Vila Itoupava,280000.0,"3 quartos | 3 vagas | 150,0 m²",Casa no Bairro Vila Itoupava em Blumenau com 3...,3.0,0.0,3.0,150.0,Casa
18158,Salto Norte,450000.0,3 quartos,Casa no Bairro Salto Norte em Blumenau com 3 D...,3.0,0.0,0.0,0.0,Casa
18159,Centro,950000.0,"4 quartos | 8 vagas | 300,0 m²",Casa no Bairro Centro em Blumenau com 4 Dormit...,4.0,0.0,8.0,300.0,Casa
18160,Água Verde,580000.0,3 quartos | 1 suíte | 2 vagas,Casa no Bairro Água Verde em Blumenau com 3 Do...,3.0,1.0,2.0,0.0,Casa
18161,Vila Nova,750000.0,2 quartos | 1 vaga,Casa no Bairro Vila Nova em Blumenau com 2 Dor...,2.0,0.0,1.0,0.0,Casa

In [109]:
imoveis = imoveis.drop(columns=['Informações', 'Descricao'])
imoveis

               Bairros   Valores  Quartos  Suítes  Vagas  Tamanho         Tipo
0      Escola Agrícola  380000.0      2.0     0.0    2.0     80.0         Casa
1                Velha  480000.0      3.0     1.0    0.0    131.0         Casa
2        Victor Konder  375000.0      2.0     1.0    1.0    124.0  Apartamento
3      Salto Weissbach  420000.0      2.0     0.0    2.0     74.0         Casa
4           Valparaiso  400000.0      5.0     0.0    3.0    200.0         Casa
...                ...       ...      ...     ...    ...      ...          ...
18157    Vila Itoupava  280000.0      3.0     0.0    3.0    150.0         Casa
18158      Salto Norte  450000.0      3.0     0.0    0.0      0.0         Casa
18159           Centro  950000.0      4.0     0.0    8.0    300.0         Casa
18160       Água Verde  580000.0      3.0     1.0    2.0      0.0         Casa
18161        Vila Nova  750000.0      2.0     0.0    1.0      0.0         Casa

[18153 rows x 7 columns]

In [110]:
imoveis = imoveis[imoveis['Tamanho'] > 40 ]
imoveis

,Bairros,Valores,Quartos,Suítes,Vagas,Tamanho,Tipo
0,Escola Agrícola,380000.0,2.0,0.0,2.0,80.0,Casa
1,Velha,480000.0,3.0,1.0,0.0,131.0,Casa
2,Victor Konder,375000.0,2.0,1.0,1.0,124.0,Apartamento
3,Salto Weissbach,420000.0,2.0,0.0,2.0,74.0,Casa
4,Valparaiso,400000.0,5.0,0.0,3.0,200.0,Casa
...,...,...,...,...,...,...,...
18152,Itoupavazinha,295000.0,2.0,2.0,2.0,73.9,Casa
18155,Itoupava Central,420000.0,2.0,0.0,1.0,86.0,Casa
18156,Água Verde,400000.0,2.0,0.0,0.0,95.0,Casa
18157,Vila Itoupava,280000.0,3.0,0.0,3.0,150.0,Casa
18159,Centro,950000.0,4.0,0.0,8.0,300.0,Casa

In [111]:
imoveis.to_csv('imoveis_limpo.csv', index=False, encoding='utf-8-sig')